security:
    factories:
          - "%kernel.root_dir%/../vendor/bundles/FOS/FacebookBundle/Resources/config/security_factories.xml"
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        "FOS\UserBundle\Model\UserInterface": sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
             
        my_fos_facebook_provider:
                id: my.facebook.user 

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false
        
        
        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: /demo/secured/login_check
                login_path: /demo/secured/login
            logout:
                path:   /demo/secured/logout
                target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"
        public:
              # since anonymous is allowed users will not be forced to login
              pattern:   .*              
              fos_facebook:
                app_url: "http://apps.facebook.com/235031239899482/"
                #app_url: "http://www.habobo.org/app_dev.php/"
                #http://habobo-ntictogolais.dotcloud.com/
                server_url: "http://www.habobo.org/app_dev.php/"                
                check_path: /login_check
                default_target_path: /
                provider: my_fos_facebook_provider
              anonymous: true
              logout:
                  handlers: ["fos_facebook.logout_handler"]


    access_control:
        - { path: /login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /habobo/, roles: IS_AUTHENTICATED_FULLY }
        #- { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }

#Facebook
fos_facebook:
      file:   %kernel.root_dir%/../vendor/facebook/src/base_facebook.php
      alias:  facebook
      app_id: 235031239899482
      secret: 01fc424d07182c19974fb0faeafb6912
      cookie: true
      permissions: [email,user_website, user_birthday, user_location,user_about_me,user_activities,user_education_history,user_interests,user_online_presence,xmpp_login]

      