parameters:
#    habobo_base.example.class: Habobo\BaseBundle\Example

services:
#    habobo_base.example:
#        class: %habobo_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
